### PR TITLE
Create data.yml

### PR DESCRIPTION
**Pull request by icf**
~

### CODE REVIEW

**Comment by icf** [comment]
!

**Comment by yanxiangyi** [comment]
Hi! Thanks for PR! Do you mind using a real name? So that we can verify if you are one of SUSTech alumni and students can contact you more conveniently. 
Plus, an avatar is prefered. If you mind providing one, can we just use your [github profile image](https://avatars0.githubusercontent.com/u/13229512?s=400&v=4)?
Thanks again for first PR!

**Comment by yanxiangyi** [comment]
And one more thing. I just queried Google Map which shows your are at Virginia. Could you please specify which university/institute you are attending? Thanks!

**Comment by icf** [comment]
Thanks

**Comment by yanxiangyi** [comment]
Thanks for PR!

**Pull request merged**
